services:
  postgres-service:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_USER=nodara_user
      - POSTGRES_PASSWORD=NodaraPass2026!
      - POSTGRES_DB=nodara_db
    ports:
      - "5432:5432"

  s4-sim-service:
    build: ./s4-sim
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://nodara_user:NodaraPass2026!@postgres-service:5432/nodara_db
    depends_on:
      - postgres-service

  langfuse-service:
    image: langfuse/langfuse:2
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://nodara_user:NodaraPass2026!@postgres-service:5432/nodara_db
      - NEXTAUTH_SECRET=super-secret-nextauth-token-2026
      - NEXTAUTH_URL=http://localhost:3000
      - SALT=${SALT}
    depends_on:
      - postgres-service

  nodara-backend-ai:
    build: ./nodara-backend
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - postgres-service
      - s4-sim-service
      - langfuse-service