apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodara-langfuse
  namespace: nodara-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
        - name: langfuse
          image: langfuse/langfuse:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nodara-enterprise-secrets
                  key: DATABASE_URL
            - name: NEXTAUTH_URL
              value: "https://langfuse-admin.c-1234567.kyma.ondemand.com"
            - name: NEXTAUTH_SECRET
              value: "enterprise_super_secret_session_string_value_for_kyma_deployment_2026"
            - name: SALT
              value: "enterprise_cryptographic_salt_for_passwords_storage_in_hana_or_postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-svc
  namespace: nodara-training
spec:
  type: ClusterIP
  selector:
    app: langfuse
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
